---
- hosts: local
  tasks:
    - name: Generate switch configs
      template: src=~/pynet-class/class5/access_switch.j2
                  dest=~/pynet-class/class5/CONFIGS/{{item.hostname}}.txt
      with_items:
        - {SNMPv3: True, hostname: pynet-sw1, secret: MySeCrEt, access_vlan: 666, ip_addr: 10.20.30.11, default_gateway: 10.20.30.1, snmp_community: MyCoMmUnItY}
        - {SNMPv3: False, hostname: pynet-sw2, secret: MySeCrEt, access_vlan: 666, ip_addr: 10.20.30.12, default_gateway: 10.20.30.1, snmp_community: MyCoMmUnItY}
        - {SNMPv3: True, hostname: pynet-sw3, secret: MySeCrEt, access_vlan: 666, ip_addr: 10.20.30.13, default_gateway: 10.20.30.1, snmp_community: MyCoMmUnItY}
        - {SNMPv3: False, hostname: pynet-sw4, secret: MySeCrEt, access_vlan: 666, ip_addr: 10.20.30.14, default_gateway: 10.20.30.1, snmp_community: MyCoMmUnItY}
        - {SNMPv3: True, hostname: pynet-sw5, secret: MySeCrEt, access_vlan: 666, ip_addr: 10.20.30.15, default_gateway: 10.20.30.1, snmp_community: MyCoMmUnItY}








